### ISSUE TITLE
Single LAN is not available for networks in passthrough mode

### ISSUE THREAD

**Issue by dvela-whg** [meraki/automation-scripts#33] opened 2022-04-06 12:21 UTC
Hi getting this error when running backup.

`appliance, getNetworkApplianceSingleLan - 400 Bad Request, {'errors': ['Single LAN is not available for networks in passthrough mode']}`

**Comment by dvela-whg** [comment] 2022-04-19 16:42
@mpapazog any feedback on this?

**Comment by mpapazog** [comment] 2022-04-19 17:03
I haven't had time to take a look at this yet.

If someone else following this thread wants to take a shot at replicating/resolving this, feel free. Probably some if-then-else code missing for handling appliance networks in passthrough mode.

**Comment by mpapazog** [comment] 2022-05-09 11:13
The error message you see is harmless and should just be ignored. The code works as intended.

What happens is the following: when instructed to fetch security appliance VLANs, the code checks if VLANs have been enabled on the network or not. Networks in passthrough mode do not have VLANs enabled, so the code will attempt to fetch any single-LAN settings instead. This operation will fail and log the error message returned by the Dashboard API. Despite the error message, the script does not stop executing or fetching any additional data, it just informs the user that this operation is invalid for this particular network.

All in all, there is nothing to fix. Just ignore the error message.

**Closed by mpapazog** 2022-05-09 11:13 UTC
